name: deploy

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  test:
    name: Test depthviz-python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - { "pythonVersion": "3.9" }
          - { "pythonVersion": "3.10" }
          - { "pythonVersion": "3.11" }
          - { "pythonVersion": "3.12" }
        poetry-version: ["1.8.5"]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.versions.pythonVersion }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies 📦
        run: |
          python -m pip install poetry
          poetry install --with dev
      - name: Check types, syntax and duckstrings 🦆
        run: |
          poetry run mypy .
          poetry run ruff check .
          poetry run interrogate --ignore-init-module --ignore-init-method --quiet --fail-under=95 .
      - name: Test depthviz with coverage 🧪
        run: poetry run coverage run --source=depthviz -m pytest . && poetry run coverage lcov -o coverage.lcov
      - name: Submit coverage report to Coveralls 📈
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./coverage.lcov
          flag-name: run-python-${{ matrix.versions.pythonVersion }}
          parallel: true
  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
  